<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HAPPYLOVER" failures="1" tests="5" name="Default test" time="45.321" errors="0" timestamp="2023-11-21T19:40:03 GMT-07:00">
  <testcase classname="tests.ContactTest" name="sign_Up_Out_Test" time="2.563"/>
  <testcase classname="tests.ContactTest" name="create_Contact_Test" time="5.957"/>
  <testcase classname="tests.ContactTest" name="can_Not_Create_Without_Mandatory_Fields_Test" time="2.576"/>
  <testcase classname="tests.ContactTest" name="edit_Exist_Contact_Test" time="4.54">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;ContactInfo [firstName=GoldaAnna, lastName=Svit, birth=1984/01/29, email=anny@gmail.com, phone=0951099819, address=Heroiv of Work, city=Kharkiv, privince=Kharkivska oblast, zip=84331, country=Ukraine]&amp;gt; but was:&amp;lt;ContactInfo [firstName=Anna, lastName=Svit, birth=1984/01/29, email=anny@gmail.com, phone=0951099819, address=Heroiv of Work, city=Kharkiv, privince=Kharkivska oblast, zip=84331, country=Ukraine]&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<ContactInfo [firstName=GoldaAnna, lastName=Svit, birth=1984/01/29, email=anny@gmail.com, phone=0951099819, address=Heroiv of Work, city=Kharkiv, privince=Kharkivska oblast, zip=84331, country=Ukraine]> but was:<ContactInfo [firstName=Anna, lastName=Svit, birth=1984/01/29, email=anny@gmail.com, phone=0951099819, address=Heroiv of Work, city=Kharkiv, privince=Kharkivska oblast, zip=84331, country=Ukraine]>
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:467)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:98)
at tests.ContactTest.edit_Exist_Contact_Test(ContactTest.java:127)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- edit_Exist_Contact_Test -->
  <testcase classname="tests.ContactTest" name="delete_Contact_Test" time="2.596"/>
</testsuite> <!-- Default test -->
